version: 2
jobs:
  one:
    docker:
      - image: ubuntu:16.10
    steps:
      - checkout
      - run: echo "A first hello"
  two:
    docker:
      - image: ubuntu:16.10
    steps:
      - checkout
      - run: echo "A second hello"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
