version: 2
jobs:
  test:
    docker:
      - image: buildpack-deps:latest
    steps:
      - checkout
      - run: cd step3and4; make clean; make test
workflows:
  version: 2
  test:
    jobs:
      - test
